name: flutter_svprogresshud
description: A clean and lightweight progress HUD for flutter app, based on SVProgressHUD.
version: 1.0.0
homepage: https://github.com/leanflutter/flutter_svprogresshud

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: org.leanflutter.plugins.flutter_svprogresshud
        pluginClass: FlutterSvprogresshudPlugin
      ios:
        pluginClass: FlutterSvprogresshudPlugin
